name: Check Publish on Release PR

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-publish:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Dart
        uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0
        env:
          # https://mise.jdx.dev/configuration/settings.html#locked
          MISE_LOCKED: "1"
          # https://mise.jdx.dev/configuration/settings.html#safe
          MISE_SAFE: "1"
        with:
          version: "2026.10.1"
          cache: false

      - name: Install dependencies
        run: dart pub get

      - name: Dry run publish
        run: dart pub publish --dry-run
