name: Check PR

on:
  pull_request:

permissions:
  contents: read
  actions: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Dart
        uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0
        env:
          # https://mise.jdx.dev/configuration/settings.html#locked
          MISE_LOCKED: "1"
          # https://mise.jdx.dev/configuration/settings.html#safe
          MISE_SAFE: "1"

      - name: Install dependencies
        run: dart pub get

      # https://github.com/invertase/github-action-dart-analyzer
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0
        with:
          fatal-infos: true

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run test
        run: dart test --file-reporter="json:test-results.json"
        continue-on-error: true

      # https://github.com/dorny/test-reporter
      - name: Report test
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: "Dart Test"
          path: "test-results.json"
          reporter: "dart-json"
          fail-on-error: "true"
